version: "3.8"

services:
  dotmarketplace-node:
    image: dotmarketplace-node
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "9944:9944"
      - "9933:9933"
    environment:
      - CARGO_HOME=/var/www/dotmarketplace-node/.cargo