version: "3.2"

services:
  dot_marketplace_node:
    image: dot_marketplace_node
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/dot-marketplace-v2/.cargo
    volumes:
      - .:/var/www/dot-marketplace-v2
    command: bash -c "cargo build --release && ./target/release/dot_marketplace_node --dev --ws-external"
